[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 5000
  flush_interval = "1m"
  flush_jitter = "5s"

[[outputs.influxdb_v2]]
  urls = ["http://${INFLUX_HOST}:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "sydmesh"
  bucket = "meshcore"

[[outputs.file]]
  files = ["/tmp/mesh_metrics.out"]
  rotation_interval = "8h"
  rotation_max_archives = 5
  data_format = "influx"

[[inputs.exec]]
  commands = ["/usr/local/bin/mc_trace.sh"]
  interval = "15m"
  timeout = "8m"
  ignore_error = true
  data_format = "influx"

[[inputs.exec]]
  commands = ["/usr/local/bin/mc_status.sh"]
  interval = "15m"
  collection_offset = "7m30s"
  timeout = "2m"
  ignore_error = true
  data_format = "influx"

